name: gri
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - cudatoolkit=11.6
  - pytorch
  - torchvision
  - torchaudio
  - tqdm
  - yacs
  - pytorch-ignite
  - numba
  - pip
  - pip:
    - timm
    - runx